[I 19:14:54.333 NotebookApp] Serving notebooks from local directory: /home/users/zg78/adver_ml
[I 19:14:54.334 NotebookApp] Jupyter Notebook 6.4.3 is running at:
[I 19:14:54.334 NotebookApp] http://linux55:8881/?token=2019bacb0ac59b14cf7dcc9ae3eb7608bf70c8439004a1f2
[I 19:14:54.334 NotebookApp]  or http://127.0.0.1:8881/?token=2019bacb0ac59b14cf7dcc9ae3eb7608bf70c8439004a1f2
[I 19:14:54.334 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 19:14:54.343 NotebookApp] 
    
    To access the notebook, open this file in a browser:
        file:///home/users/zg78/.local/share/jupyter/runtime/nbserver-17742-open.html
    Or copy and paste one of these URLs:
        http://linux55:8881/?token=2019bacb0ac59b14cf7dcc9ae3eb7608bf70c8439004a1f2
     or http://127.0.0.1:8881/?token=2019bacb0ac59b14cf7dcc9ae3eb7608bf70c8439004a1f2
/home/users/zg78/_conda/envs/base_torch/lib/python3.6/json/encoder.py:257: UserWarning: date_default is deprecated since jupyter_client 7.0.0. Use jupyter_client.jsonutil.json_default.
  return _iterencode(o, 0)
[W 19:17:50.252 NotebookApp] Notebook baseline/test_pipeline.ipynb is not trusted
[I 19:17:50.450 NotebookApp] Kernel started: 6321accb-62eb-4a75-88a4-22bd6e175e38, name: python3
ERROR:asyncio:Exception in callback <TaskStepMethWrapper object at 0x7fe92f513c88>()
handle: <Handle <TaskStepMethWrapper object at 0x7fe92f513c88>()>
Traceback (most recent call last):
  File "/home/users/zg78/_conda/envs/base_torch/lib/python3.6/asyncio/events.py", line 145, in _run
    self._callback(*self._args)
KeyError: <_UnixSelectorEventLoop running=True closed=False debug=False>
/home/users/zg78/_conda/envs/base_torch/lib/python3.6/json/encoder.py:257: UserWarning: date_default is deprecated since jupyter_client 7.0.0. Use jupyter_client.jsonutil.json_default.
  return _iterencode(o, 0)
[I 19:19:50.450 NotebookApp] Saving file at /baseline/test_pipeline.ipynb
[I 19:21:50.442 NotebookApp] Saving file at /baseline/test_pipeline.ipynb
